/* Automatically generated by po2tbl.sed from power-applet.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"N/A", 2},
  {"Battery charge is down to %d percent", 3},
  {"Battery fully charged", 4},
  {"No themes installed", 5},
  {"No power management was found", 6},
  {"PowerApplet properties", 7},
  {"Power Applet", 8},
  {"(C) 2001 Free Software Foundation ", 9},
  {"\
Yet another applet that shows the\n\
waterlevel in Sortedamssøen.", 10},
  {"Properties...", 11},
  {"About...", 12},
  {"Can't create applet!\n", 13},
  {"Theme", 14},
  {"Show battery charge in percentage", 15},
  {"Show time remaining", 16},
  {"Show AC if charging", 17},
  {"Show full charge message", 18},
  {"Show low charge message", 19},
  {"Flash text red when low", 20},
  {"Antialiase text", 21},
  {"Appearance", 22},
  {"Update interval (secs)", 23},
  {"Low power threshold", 24},
  {"Advanced", 25},
};

int _msg_tbl_length = 25;
