/* Automatically generated by po2tbl.sed from power-applet.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"N/A", 2},
  {"No themes installed", 3},
  {"Cannot open /proc/apm", 4},
  {"No power management was found", 5},
  {"PowerApplet properties", 6},
  {"Power Applet", 7},
  {"(C) 2001 Free Software Foundation ", 8},
  {"blablabla", 9},
  {"Properties...", 10},
  {"About...", 11},
  {"Can't create applet!\n", 12},
  {"Theme", 13},
  {"Show battery charge in percentage", 14},
  {"Show time remaining", 15},
  {"Show AC if charging", 16},
  {"Show full charge message", 17},
  {"Show low charge message", 18},
  {"Flash text red when low", 19},
  {"Antialiase text", 20},
  {"Appearance", 21},
  {"Update interval (secs)", 22},
  {"Low power threshold", 23},
  {"Advanced", 24},
};

int _msg_tbl_length = 24;
