/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Theme");
gchar *s = N_("Show battery charge in percentage");
gchar *s = N_("Show time remaining");
gchar *s = N_("Show AC if charging");
gchar *s = N_("Show full charge message");
gchar *s = N_("Show low charge message");
gchar *s = N_("Flash text red when low");
gchar *s = N_("Antialiase text");
gchar *s = N_("Appearance");
gchar *s = N_("Update interval (secs)");
gchar *s = N_("Low power threshold");
gchar *s = N_("Advanced");
